# Generated by Django 3.1.3 on 2020-12-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Service',
        ),
    ]
